# Generated by Django 5.2.4 on 2025-07-05 15:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'メニューカテゴリ',
                'verbose_name_plural': 'メニューカテゴリ',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='価格')),
                ('description', models.TextField(blank=True, verbose_name='商品詳細')),
                ('allergens', models.JSONField(blank=True, default=list, help_text='含まれるアレルギー物質', verbose_name='アレルギー物質')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='ビーガン対応')),
                ('contains_pork', models.BooleanField(default=False, verbose_name='豚肉含有')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_available', models.BooleanField(default=True, verbose_name='提供可能')),
            ],
            options={
                'verbose_name': 'メニュー項目',
                'verbose_name_plural': 'メニュー項目',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='app.menucategory')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.menuitem')),
            ],
            options={
                'verbose_name': 'メニュー項目カテゴリ',
                'verbose_name_plural': 'メニュー項目カテゴリ',
                'unique_together': {('menu_item', 'category')},
            },
        ),
    ]
