# Generated by Django 5.2.4 on 2025-07-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='コンテンツタイプ')),
                ('object_id', models.PositiveIntegerField(verbose_name='オブジェクトID')),
                ('field_name', models.CharField(max_length=50, verbose_name='フィールド名')),
                ('source_text', models.TextField(verbose_name='元のテキスト')),
                ('target_language', models.CharField(max_length=10, verbose_name='翻訳先言語')),
                ('translated_text', models.TextField(verbose_name='翻訳されたテキスト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '翻訳キャッシュ',
                'verbose_name_plural': '翻訳キャッシュ',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'field_name', 'target_language'], name='app_transla_content_522fa9_idx')],
                'unique_together': {('content_type', 'object_id', 'field_name', 'target_language')},
            },
        ),
    ]
